"""

Note: Documentation automatically generated by https://undoc.ai
"""
class BaseLanguage:
    def __init__(self):
        pass

    def run(self, code):
        pass

    def stop(self):
        pass

    def terminate(self):
        pass
