"""

Note: Documentation automatically generated by https://undoc.ai
"""
import os
import tempfile


def cleanup_temporary_file(temp_file_name, verbose=False):

    try:
        # clean up temporary file
        os.remove(temp_file_name)

        if verbose:
            print(f"Cleaning up temporary file {temp_file_name}")
            print("---")

    except Exception as e:
        print(f"Could not clean up temporary file.")
        print(e)
        print("")


def create_temporary_file(contents, extension=None, verbose=False):
    """
    Creates a temporary file with specified contents and extension.
        This function generates a temporary file using the `tempfile` module, writes the given
        contents into the file, and then closes it. If a file extension is specified, it appends
        the extension to the file name. The function returns the name of the temporary file for
        later use. In case of an error during the file creation process, the function prints an
        error message along with the exception message.
        Args:
            contents (str): The content to be written into the temporary file.
            extension (str, optional): The file extension to be appended to the file name. If not provided,
                no extension is appended.
            verbose (bool): If True, prints messages about the file creation process; otherwise, remains silent.
        Returns:
            str: The file name of the created temporary file.
        Raises:
            Exception: If an error occurs during the file creation, an error is printed along with the
                exception message, but the error is not propagated upwards.
    """

    try:
        # Create a temporary file
        with tempfile.NamedTemporaryFile(
            mode="w", delete=False, suffix=f".{extension}" if extension else ""
        ) as f:
            f.write(contents)
            temp_file_name = f.name
            f.close()

        if verbose:
            print(f"Created temporary file {temp_file_name}")
            print("---")

        return temp_file_name

    except Exception as e:
        print(f"Could not create temporary file.")
        print(e)
        print("")
